#pragma once

inline std::unordered_map<int, std::string> nameOfBlockId =
{
    //{0, "air"},
    {1, "stone"},
    {2, "grass"},
    {3, "dirt"},
    {4, "cobblestone"},
    {5, "wood"},
    {6, "sapling"},
    {7, "bedrock"},
    {8, "water"},
    {9, "stationary water"},
    {10, "lava"},
    {11, "stationary lava"},
    {12, "sand"},
    {13, "gravel"},
    {14, "gold ore"},
    {15, "iron ore"},
    {16, "coal ore"},
    {17, "log"},
    {18, "leaves"},
    {19, "sponge"},
    {20, "glass"},
    {21, "lapis ore"},
    {22, "lapis block"},
    {23, "dispenser"},
    {24, "sandstone"},
    {25, "noteblock"},
    {26, "bed"},
    {27, "golden_rail"},
    {28, "detector_rail"},
    {29, "sticky_piston"},
    {30, "web"},
    {31, "tall grass"},
    {32, "dead bush"},
    {33, "piston"},
    {34, "piston head"},
    {35, "wool"},
    {36, "moving piston"},
    {37, "dandelion"},
    {38, "poppy"},
    {39, "brown mushroom"},
    {40, "red mushroom"},
    {41, "gold block"},
    {42, "iron block"},
    {43, "double stone slab"},
    {44, "stone slab"},
    {45, "brick"},
    {46, "tnt"},
    {47, "bookshelf"},
    {48, "moss stone"},
    {49, "obsidian"},
    {50, "torch"},
    {51, "fire"},
    {52, "monster spawner"},
    {53, "oak wood stairs"},
    {54, "chest"},
    {55, "redstone wire"},
    {56, "diamond ore"},
    {57, "diamond block"},
};
